### ISSUE TITLE
~ 3/23(수) 까지 해올 것

### ISSUE THREAD

**Issue by zhenying2** [dsc-sookmyung/2022-NoLFI-SolutionChallenge#15]
주은
- [x] 마이페이지 UI 만들기

진영 (주은 branch 참고 -> 코드 잡아서 merge)
- [x] 메인페이지들 간의 연결 버그 잡아보기

경민
- [x] 가입자에 따라 달라지는 회원가입 db 생성

**Comment by Jueunkim429** [comment]
뒤로가기 빼고 완료. 
내역 보이는거는 우선 기존코드(엉망인거) 복붙함 -> 오류잡으면 다시 해보기

**Comment by kyungminlee-12** [comment]
firebase에 폴더를 분리해서 가입자에 따라 달리지는 db 생성했습니다!!
